### ISSUE TITLE
Screenshot pls ;)

### ISSUE THREAD

**Issue by max107** [allanks/Voxel-Engine#44]

**Comment by allanks** [comment]
Been a while since I touched this. Here a screenshot of the game currently.

![gamescreenshot](https://cloud.githubusercontent.com/assets/7260399/8155080/afdb64fe-1394-11e5-80f2-4bec72596c7b.JPG)

And some console output.
![consolecapture](https://cloud.githubusercontent.com/assets/7260399/8155083/c5377798-1394-11e5-891d-7d12aad3197a.JPG)

I am on a windows/arch linux machine as my test environments, so haven't tested on mac yet
